# AUTO-GENERATED by key_manager.ps1 on 2026-08-18 01:16:41
# This script contains the master public key embedded for client setup# setup_windows_ssh.ps1
# Register this Windows machine as an SSH-controlled client. Run ONCE as Administrator.
# Requirements: Windows 10/11, admin rights, internet access (for install).
#
# USAGE:
#   1. On the master PC, paste the content of ~/.ssh/id_ed25519.pub into $PublicKey below
#      (or set $PubKeyUrl to a plain-text URL serving the public key).
#   2. Copy THIS file to the client machine and run: right-click -> Run with PowerShell (Admin)
#      (or double-click run_setup.bat).
#   3. Done. Master can now: ssh <user>@<this-machine-ip>
#
# Notes:
#   - For admin users Windows OpenSSH reads C:\ProgramData\ssh\administrators_authorized_keys
#     (NOT ~/.ssh/authorized_keys). ACL must be Administrators + SYSTEM only, else sshd
#     silently ignores the file. Both locations are configured below.
#   - dism.exe is used instead of Add-WindowsCapability (DISM cmdlets fail with
#     "Class not registered" under PowerShell 7).
#   - Password authentication is disabled: the only way in is the master's key.
#   - A log is written to C:\ProgramData\ssh\setup.log.

param(
    [string]$PublicKey = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKrGwHBLLLjMdHy9UwXxq+CjdwwwhO8YPcaHMDscks79 mrken@MRKENT',
    [string]$PubKeyUrl = ''
)

$ErrorActionPreference = 'Stop'

# ===== CONFIG (override via param -PublicKey, master.pub, or $PubKeyUrl) =====
# Auto-generate key if placeholder or empty
if (-not $PublicKey -or $PublicKey -like '*REPLACE_WITH_MASTER_PUBKEY*') { 
    $PublicKey = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKrGwHBLLLjMdHy9UwXxq+CjdwwwhO8YPcaHMDscks79 mrken@MRKENT' 
}

$sshDir = "$env:ProgramData\ssh"
$logFile = Join-Path $sshDir 'setup.log'
New-Item -ItemType Directory -Force -Path $sshDir | Out-Null

function Log {
    param([string]$Message, [string]$Color = 'Gray')
    $line = "[{0}] {1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message
    Add-Content $logFile $line
    Write-Host $line -ForegroundColor $Color
}

function Fail {
    param([string]$Message)
    Log $Message 'Red'
    exit 1
}

# ===== 1. Admin check =====
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { Fail 'ERROR: run this script as Administrator.' }

# ===== 2. Install OpenSSH Server if missing =====
if (-not (Get-Service sshd -ErrorAction SilentlyContinue)) {
    Log 'Installing OpenSSH Server...'
    dism.exe /online /add-capability /capabilityname:OpenSSH.Server~~~~0.0.1.0
    if ($LASTEXITCODE -ne 0) { Fail 'ERROR: OpenSSH Server install failed.' }
    Log 'OpenSSH Server installed.'
} else {
    Log 'OpenSSH Server already installed.'
}

# ===== 3. Enable + start sshd (verify it is actually running) =====
Set-Service sshd -StartupType Automatic
Start-Service sshd
Start-Sleep -Seconds 2
if ((Get-Service sshd).Status -ne 'Running') { Fail 'ERROR: sshd service did not start.' }
Log 'sshd service is running (automatic start).'

# ===== 4. Firewall: ensure inbound rule for port 22 (install usually creates it) =====
if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue)) {
    New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH SSH Server' `
        -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 | Out-Null
}
$fwRule = Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP'
if (-not ($fwRule.Enabled -and $fwRule.Action -eq 'Allow')) { Fail 'ERROR: firewall rule not enabled.' }
Log 'Firewall rule OpenSSH-Server-In-TCP (port 22) is enabled.'

# ===== 5. Resolve master public key (param > master.pub > URL > hardcoded placeholder) =====
if (-not $PublicKey -or $PublicKey -like '*REPLACE_WITH_MASTER_PUBKEY*') {
    $sidecar = Join-Path $PSScriptRoot 'master.pub'
    if (Test-Path $sidecar) { $PublicKey = (Get-Content $sidecar -Raw).Trim() }
}
if (-not $PublicKey -or $PublicKey -like '*REPLACE_WITH_MASTER_PUBKEY*') {
    if ($PubKeyUrl) { $PublicKey = (Invoke-WebRequest -Uri $PubKeyUrl -UseBasicParsing).Content.Trim() }
}
if (-not $PublicKey -or $PublicKey -like '*REPLACE_WITH_MASTER_PUBKEY*') {
    Fail 'ERROR: no public key found. Options: (1) pass -PublicKey param, (2) place master.pub next to this script, (3) set $PubKeyUrl, (4) edit the placeholder.'
}
if ($PublicKey -notmatch '^ssh-(ed25519|rsa|ecdsa) ') { Fail 'ERROR: public key does not look valid.' }

# ===== 6. Install key for Administrators (used when the SSH user is an admin) =====
$adminKeys = Join-Path $sshDir 'administrators_authorized_keys'
if (Test-Path $adminKeys) {
    if ((Get-Content $adminKeys -Raw) -notmatch [regex]::Escape($PublicKey)) {
        Add-Content $adminKeys $PublicKey
    }
} else {
    Set-Content $adminKeys $PublicKey
}
icacls $adminKeys /inheritance:r /grant 'Administrators:F' /grant 'SYSTEM:F' | Out-Null
if ((Get-Content $adminKeys -Raw) -notmatch [regex]::Escape($PublicKey)) { Fail 'ERROR: failed to write administrators_authorized_keys.' }
Log "Master key added to $adminKeys (ACL: Administrators + SYSTEM)."

# ===== 7. Also install for the current user profile (non-admin fallback) =====
$userSsh = "$env:USERPROFILE\.ssh"
New-Item -ItemType Directory -Force -Path $userSsh | Out-Null
$userKeys = Join-Path $userSsh 'authorized_keys'
if (Test-Path $userKeys) {
    if ((Get-Content $userKeys -Raw) -notmatch [regex]::Escape($PublicKey)) {
        Add-Content $userKeys $PublicKey
    }
} else {
    Set-Content $userKeys $PublicKey
}
icacls $userSsh /inheritance:r /grant "$($env:USERNAME):(OI)(CI)F" | Out-Null
icacls $userKeys /inheritance:r /grant "$($env:USERNAME):F" /grant 'SYSTEM:F' /grant 'Administrators:F' | Out-Null
Log "Master key also added to $userKeys."

# ===== 8. Hardening: key-only + brute-force protection + keepalive =====
$sshdCfg = Join-Path $sshDir 'sshd_config'
if (Test-Path $sshdCfg) {
    $cfg = Get-Content $sshdCfg -Raw

    # Ensure PasswordAuthentication no (first-wins: replace any 'yes', else prepend)
    if ($cfg -notmatch '(?m)^\s*PasswordAuthentication\s+no\s*(#|$)') {
        $cfg = $cfg -replace '(?m)^\s*#?\s*PasswordAuthentication\s+yes\s*$', 'PasswordAuthentication no'
        if ($cfg -notmatch '(?m)^\s*PasswordAuthentication\s+no\s*$') {
            $cfg = "PasswordAuthentication no`n" + $cfg
        }
    }

    # Other hardening directives MUST be in GLOBAL scope (before any Match block).
    # Windows sshd_config ends with a 'Match Group administrators' block, so we
    # PREPEND these to the top instead of appending (appending lands inside Match
    # and sshd -t rejects it: "Directive not allowed within a Match block").
    $toAdd = @()
    if ($cfg -notmatch '(?m)^\s*MaxAuthTries\s+\d')       { $toAdd += 'MaxAuthTries 3' }
    if ($cfg -notmatch '(?m)^\s*LoginGraceTime\s+\d')     { $toAdd += 'LoginGraceTime 30' }
    if ($cfg -notmatch '(?m)^\s*ClientAliveInterval\s+\d') { $toAdd += 'ClientAliveInterval 60' }
    if ($cfg -notmatch '(?m)^\s*ClientAliveCountMax\s+\d') { $toAdd += 'ClientAliveCountMax 3' }

    if ($toAdd.Count -gt 0) {
        $block = "# --- hardening added by setup_windows_ssh.ps1 ---`n" + ($toAdd -join "`n")
        $cfg = $block + "`n" + $cfg
    }

    Set-Content $sshdCfg $cfg -Encoding ascii
}
$sshdExe = Join-Path $env:SystemRoot 'System32\OpenSSH\sshd.exe'
if (Test-Path $sshdExe) {
    & $sshdExe -t
    if ($LASTEXITCODE -ne 0) { Fail 'ERROR: sshd_config invalid, SSH login may fail. Use RDP/console to fix.' }
}
Restart-Service sshd
Start-Sleep -Seconds 2
if ((Get-Service sshd).Status -ne 'Running') { Fail 'ERROR: sshd did not restart.' }
Log 'Password authentication disabled; sshd restarted with new config.'

Log 'Client registered successfully.' 'Green'
Log "Master can now SSH in as: ssh $env:USERNAME@<this-machine-ip>" 'Cyan'
Log 'If SSH login fails, use RDP/console (password auth is now disabled).' 'Yellow'

# ===== 9. Report IP info (helps master update hosts.yaml) =====
$localIps = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.IPAddress -notlike '127.*' -and $_.PrefixOrigin -ne 'WellKnown' } |
    Select-Object -ExpandProperty IPAddress
$localIp = ($localIps | Select-Object -First 1)
Log "This machine local IP(s): $($localIps -join ', ')" 'Cyan'
try {
    $publicIp = (Invoke-RestMethod -Uri 'https://api.ipify.org' -TimeoutSec 10)
    Log "This machine public IP: $publicIp" 'Cyan'
    Log "Add to hosts.yaml:  host: $publicIp  |  user: $env:USERNAME" 'Cyan'
    if ($localIp) { Log "Or via reverse tunnel: ssh -p 2201 $env:USERNAME@<relay-ip>  (see reverse_tunnel.ps1)" 'Cyan' }
} catch {
    Log 'Could not reach api.ipify.org — check this machine IP manually.' 'Yellow'
}
